services:
  - 'mysql:5.7'
  
variables:
  MYSQL_HOST: localhost
  MYSQL_DATABASE: keep_note6
  MYSQL_CI_URL: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}
  MYSQL_USER: root
  MYSQL_PASSWORD: root

stages:
 
  - test
  - build

maven-test:
    image: java:8-jdk
    image: maven:3-jdk-8
    stage: test
    cache:
        paths:
          - .m2/repository
          - target
    before_script:
      - cd KeepNote-Step6-Boilerplate
    script: "mvn test -B"

maven-build:
    image: java:8-jdk
    image: maven:3-jdk-8
    stage: build
    cache:
        paths:
          - .m2/repository
          - target
    before_script:
      - cd KeepNote-Step6-Boilerplate      
    script: "mvn package -U"
    artifacts:
        paths:
        - target/*.jar
